
message(STATUS "Platform is emscripten for engine")

include("${CMAKE_SOURCE_DIR}/cmake/DownloadSDL2_NJLIC.cmake")
list(APPEND ${CMAKE_PROJECT_NAME}_THIRDPARTY_INCLUDE_DIRS "${SDL2_INCLUDE_DIRS}")

find_package(SDL2_NJLIC REQUIRED)
list(APPEND EXTRA_LIBS ${SDL2_TARGETS})

SOURCE_GROUP("THIRDPARTY\\SDL2" FILES ${SDL2_INCLUDE_FILES} )
