if(EMSCRIPTEN)
  include("${CMAKE_SOURCE_DIR}/cmake/emscripten_external_libraries.cmake")
elseif(WINDOWS)
  if(ARCH_64)
    include("${CMAKE_SOURCE_DIR}/cmake/windows64_external_libraries.cmake")
  else()
    include("${CMAKE_SOURCE_DIR}/cmake/windows32_external_libraries.cmake")
  endif()
elseif(APPLE)
  if(IOS)
    include("${CMAKE_SOURCE_DIR}/cmake/ios_external_libraries.cmake")
  elseif(TVOS)
    include("${CMAKE_SOURCE_DIR}/cmake/appletv_external_libraries.cmake")
  else()
    include("${CMAKE_SOURCE_DIR}/cmake/macos_external_libraries.cmake")
  endif()
elseif(UNIX AND NOT APPLE AND NOT ANDROID)
  if(LINUX)
    include("${CMAKE_SOURCE_DIR}/cmake/linux_external_libraries.cmake")
  elseif(UNIX)
    include("${CMAKE_SOURCE_DIR}/cmake/unix_external_libraries.cmake")
  endif()
elseif(ANDROID)
  include("${CMAKE_SOURCE_DIR}/cmake/android_external_libraries.cmake")
endif()


