if(EMSCRIPTEN)
  include("cmake/emscripten_external_libraries.cmake")
elseif(WINDOWS)
  if(ARCH_64)
    include("cmake/windows64_external_libraries.cmake")
  else()
    include("cmake/windows32_external_libraries.cmake")
  endif()
elseif(APPLE)
  if(IOS)
    include("cmake/ios_external_libraries.cmake")
  elseif(TVOS)
    include("cmake/appletv_external_libraries.cmake")
  else()
    include("cmake/macos_external_libraries.cmake")
  endif()
elseif(UNIX AND NOT APPLE AND NOT ANDROID)
  if(LINUX)
    include("cmake/linux_external_libraries.cmake")
  elseif(UNIX)
    include("cmake/unix_external_libraries.cmake")
  endif()
elseif(ANDROID)
  include("cmake/android_external_libraries.cmake")
endif()


